#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Aug 24 14:23:55 -03 2023
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b29828e3f33d4d20b2f3431d57d4161f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tcc_tb_behav xil_defaultlib.tcc_tb -log elaborate.log"
xelab -wto b29828e3f33d4d20b2f3431d57d4161f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tcc_tb_behav xil_defaultlib.tcc_tb -log elaborate.log

